-- Auto-generated from lib/data.ts — do not hand-edit, re-run scripts/gen-seed.ts instead
begin;
truncate table demand, feedback, skills, courses, roles, majors restart identity cascade;

-- majors
insert into majors (id, name, school, ready, note) values ('cs-tu', 'วิทยาการคอมพิวเตอร์', 'คณะวิทยาศาสตร์และเทคโนโลยี มธ.', true, 'หลักสูตรปรับปรุง พ.ศ. 2566 · ข้อมูลรายวิชาอ้างอิงเอกสารจริง');
insert into majors (id, name, school, ready, note) values ('it-tu', 'เทคโนโลยีสารสนเทศ', 'คณะวิทยาศาสตร์และเทคโนโลยี มธ.', false, NULL);
insert into majors (id, name, school, ready, note) values ('ce', 'วิศวกรรมคอมพิวเตอร์', 'คณะวิศวกรรมศาสตร์', false, NULL);
insert into majors (id, name, school, ready, note) values ('stat', 'สถิติประยุกต์ / วิทยาการข้อมูล', 'คณะสถิติประยุกต์', false, NULL);

-- courses
insert into courses (code, name, when_label, ord) values ('คพ.103', 'การโปรแกรมคอมพิวเตอร์เบื้องต้น · Introduction to Computer Programming', 'ปี 1 · เทอม 1', 11);
insert into courses (code, name, when_label, ord) values ('คพ.100', 'การพัฒนาเว็บแอปพลิเคชันเบื้องต้น · Basic Web Development', 'ปี 1 · เทอม 2', 12);
insert into courses (code, name, when_label, ord) values ('คพ.111', 'แนวคิดเชิงวัตถุ · Object-Oriented Concepts', 'ปี 1 · เทอม 2', 12);
insert into courses (code, name, when_label, ord) values ('คพ.216', 'โครงสร้างข้อมูลและขั้นตอนวิธี · Data Structures and Algorithms', 'ปี 2 · เทอม 1', 21);
insert into courses (code, name, when_label, ord) values ('คพ.240', 'หลักการวิทยาการข้อมูล · Principles of Data Science', 'ปี 2 · เทอม 1', 21);
insert into courses (code, name, when_label, ord) values ('คพ.251', 'ระบบฐานข้อมูล 1 · Database Systems 1', 'ปี 2 · เทอม 2', 22);
insert into courses (code, name, when_label, ord) values ('คพ.234', 'เครือข่ายคอมพิวเตอร์และความปลอดภัยทางไซเบอร์ · Computer Network and Cyber-Security', 'ปี 2 · เทอม 2', 22);
insert into courses (code, name, when_label, ord) values ('คพ.232', 'เทคโนโลยีกลุ่มเมฆเบื้องต้น · Introduction to Cloud Computing', 'ปี 2 · เทอม 2', 22);
insert into courses (code, name, when_label, ord) values ('คพ.261', 'วิศวกรรมซอฟต์แวร์เบื้องต้น · Introduction to Software Engineering', 'ปี 3 · เทอม 1', 31);
insert into courses (code, name, when_label, ord) values ('คพ.365', 'กระบวนการและไปป์ไลน์เดฟออปส์ · DevOps Pipelines and Processes', 'ปี 3 · เทอม 1', 31);
insert into courses (code, name, when_label, ord) values ('คพ.262', 'การทดสอบซอฟต์แวร์เบื้องต้น · Introduction to Software Testing', 'ปี 3 · เทอม 2', 32);
insert into courses (code, name, when_label, ord) values ('คพ.224', 'การดูแลและติดตามประสิทธิภาพระบบปฏิบัติการ · Linux Administration and Performance Monitoring', 'ปี 3 · เทอม 2', 32);
insert into courses (code, name, when_label, ord) values ('คพ.341', 'วิศวกรรมข้อมูลขนาดใหญ่ · Big Data Engineering', 'ปี 3 · เทอม 2', 32);
insert into courses (code, name, when_label, ord) values ('คพ.347', 'คลังข้อมูลและอัจฉริยะทางธุรกิจ · Data Warehousing and Business Intelligence', 'ปี 3 · เทอม 2', 32);
insert into courses (code, name, when_label, ord) values ('คพ.354', 'ระบบฐานข้อมูล 2 · Database Systems 2', 'ปี 3 · เทอม 2', 32);
insert into courses (code, name, when_label, ord) values ('คพ.246', 'การแสดงข้อมูล · Data Visualization', 'ปี 3 · เทอม 2', 32);
insert into courses (code, name, when_label, ord) values ('คพ.361', 'สถาปัตยกรรมซอฟต์แวร์บนคลาวด์ · Cloud-Based Software Architecting', 'ปี 3 · เทอม 2', 32);
insert into courses (code, name, when_label, ord) values ('คพ.372', 'การเรียนรู้ของเครื่อง · Machine Learning', 'ปี 3 · เทอม 2', 32);
insert into courses (code, name, when_label, ord) values ('คพ.343', 'การเรียนรู้เชิงลึก · Applied Deep Learning', 'ปี 4 · เทอม 1', 41);
insert into courses (code, name, when_label, ord) values ('คพ.367', 'แนวคิดการพัฒนาเว็บบริการ · Web Service Development Concepts', 'ปี 3 · เทอม 2', 32);

-- skills
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('SQL', 'คพ.251', 'คพ.251 ระบบฐานข้อมูล 1', 'หลักสูตรเขียนว่า “ภาษาสอบถาม / query languages” — คำว่า SQL ไม่ปรากฏในเอกสารหลักสูตรเลยแม้แต่ครั้งเดียว (ค้นทั้ง 162 หน้า)', NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Python', 'คพ.103', 'คพ.103 การโปรแกรมคอมพิวเตอร์เบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Python / scripting', 'คพ.103', 'คพ.103 การโปรแกรมคอมพิวเตอร์เบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('REST API', 'คพ.100', 'คพ.100 การพัฒนาเว็บแอปพลิเคชันเบื้องต้น', 'หลักสูตรเขียนว่า “เว็บแอปพลิเคชัน” — คำว่า REST ไม่ปรากฏในเอกสารหลักสูตรเลย', NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('OOP / design patterns', 'คพ.111', 'คพ.111 แนวคิดเชิงวัตถุ', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('โครงสร้างข้อมูล / อัลกอริทึม', 'คพ.216', 'คพ.216 โครงสร้างข้อมูลและขั้นตอนวิธี', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('สถิติเชิงพรรณนา', 'คพ.240', 'คพ.240 หลักการวิทยาการข้อมูล', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('คณิตศาสตร์ / สถิติ', 'คพ.240', 'คพ.240 หลักการวิทยาการข้อมูล', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Networking พื้นฐาน', 'คพ.234', 'คพ.234 เครือข่ายคอมพิวเตอร์และความปลอดภัยทางไซเบอร์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Cloud พื้นฐาน', 'คพ.232', 'คพ.232 เทคโนโลยีกลุ่มเมฆเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Git / version control', 'คพ.365', 'คพ.365 กระบวนการและไปป์ไลน์เดฟออปส์', 'เอกสารหลักสูตรเขียนว่า “การควบคุมเวอร์ชันของโค้ดด้วยกิท” — ทับศัพท์ไทย ค้นคำว่า Git ไม่เจอ', 'คพ.365 หน้า 74 · ฉบับอังกฤษเขียน code version control/git', true, true, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Docker', 'คพ.365', 'คพ.365 กระบวนการและไปป์ไลน์เดฟออปส์', 'เอกสารหลักสูตรเขียนว่า “คอนเทนเนอร์” — ชื่อหมวดหมู่ ไม่ใช่ชื่อผลิตภัณฑ์ ค้นคำว่า Docker ไม่เจอ', 'คพ.365 หน้า 74 · ฉบับอังกฤษเขียน container', true, true, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('CI/CD', 'คพ.365', 'คพ.365 กระบวนการและไปป์ไลน์เดฟออปส์', 'เอกสารหลักสูตรเขียนว่า “การสร้างซีไอซีดีไปป์ไลน์” — ทับศัพท์ไทย ค้นคำว่า CI/CD ไม่เจอ', 'คพ.365 หน้า 74 · ฉบับอังกฤษเขียน CI/CD pipeline', true, true, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Unit testing', 'คพ.261', 'คพ.261 วิศวกรรมซอฟต์แวร์เบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Data warehouse concepts', 'คพ.251', 'คพ.251 ครอบคลุมบางส่วน', NULL, NULL, false, false, true, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Cloud (AWS / GCP)', 'คพ.361', 'คพ.361 สถาปัตยกรรมซอฟต์แวร์บนคลาวด์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Apache Spark', 'คพ.341', 'คพ.341 วิศวกรรมข้อมูลขนาดใหญ่', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('ETL / data pipeline', 'คพ.341', 'คพ.341 วิศวกรรมข้อมูลขนาดใหญ่', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Data cleaning / wrangling', 'คพ.341', 'คพ.341 วิศวกรรมข้อมูลขนาดใหญ่', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('การนำเสนอข้อมูลด้วยภาพ', 'คพ.246', 'คพ.246 การแสดงข้อมูล', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Machine learning พื้นฐาน', 'คพ.372', 'คพ.372 การเรียนรู้ของเครื่อง', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Deep learning', 'คพ.343', 'คพ.343 การเรียนรู้เชิงลึก', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Data modeling', 'คพ.354', 'คพ.354 ระบบฐานข้อมูล 2', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Linux / shell', 'คพ.224', 'คพ.224 การดูแลและติดตามประสิทธิภาพระบบปฏิบัติการ', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Java / Spring Boot', NULL, 'หลักสูตรสอน OOP แต่ไม่สอนเฟรมเวิร์กนี้', 'ค้นคำว่า “Spring” ในเอกสารหลักสูตรทั้งฉบับ = พบ 0 ครั้ง · คำว่า “Java” พบ 1 ครั้ง อยู่ในคำว่า JavaScript', NULL, false, false, false, 'course', 'ประกาศเขียนว่า "เคยใช้ Spring Boot ในโปรเจกต์จริง" ไม่ใช่ "จบสาย Java" — หลักสูตรให้พื้น OOP มาแล้ว เหลือแค่เฟรมเวิร์ก', 'เขียน REST API ตัวที่เคยทำในวิชา คพ.100 ใหม่ด้วย Spring Boot ให้จบทั้งตัว', 'ประมาณ 1–2 สุดสัปดาห์ · ได้ repo เป็นหลักฐาน', NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Kubernetes', NULL, 'ไม่มีวิชาไหนในหลักสูตรสอน', 'ค้นคำว่า “Kubernetes” ในเอกสารหลักสูตร = พบ 0 ครั้ง', NULL, false, false, false, 'course', NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Terraform / IaC', NULL, 'ไม่มีวิชาไหนในหลักสูตรสอน', NULL, NULL, false, false, false, 'course', NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Apache Kafka', NULL, 'ไม่มีวิชาไหนในหลักสูตรสอน', NULL, NULL, false, false, false, 'course', NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Message queue (Kafka / RabbitMQ)', NULL, 'คพ.366 กล่าวถึงคิวข้อความ แต่ไม่ระบุเครื่องมือ', 'เอกสารเขียนว่า “สถาปัตยกรรมแบบแยกส่วนด้วยการใช้คิวข้อความ” — ไม่มีชื่อผลิตภัณฑ์', NULL, false, false, false, 'course', NULL, NULL, NULL, NULL);
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('สื่อสารกับ stakeholder', NULL, 'ได้จากการทำงานจริงเท่านั้น', NULL, NULL, false, false, false, 'work', NULL, NULL, NULL, 'ฝึกงาน ปี 3 หรือรับงานที่มีลูกค้าจริง');
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Requirements gathering', NULL, 'ได้จากการทำงานจริงเท่านั้น', NULL, NULL, false, false, false, 'work', NULL, NULL, NULL, 'รับงาน freelance หรือทำโปรเจกต์ให้หน่วยงานจริงในมหาวิทยาลัย');
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('อ่านและ implement งานวิจัย', NULL, 'ได้จากโครงงานหรือแล็บวิจัย', NULL, NULL, false, false, false, 'work', NULL, NULL, NULL, 'ขอเข้าแล็บอาจารย์ หรือทำโปรเจกต์ปี 4 สายนี้');
insert into skills (key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('Cost estimation / TCO', NULL, 'ได้จากการทำงานจริงเท่านั้น', NULL, NULL, false, false, false, 'work', NULL, NULL, NULL, 'ต้องเคยเสนอราคาให้ลูกค้าจริง');

-- roles
insert into roles (id, name, posts, jr_posts, fit) values ('de', 'Data Engineer', 480, 214, 1);
insert into roles (id, name, posts, jr_posts, fit) values ('be', 'Software Engineer (Backend)', 1240, 612, 2);
insert into roles (id, name, posts, jr_posts, fit) values ('da', 'Data Analyst', 610, 341, 3);
insert into roles (id, name, posts, jr_posts, fit) values ('ml', 'ML Engineer', 210, 74, 4);
insert into roles (id, name, posts, jr_posts, fit) values ('do', 'DevOps / SRE', 390, 118, 5);
insert into roles (id, name, posts, jr_posts, fit) values ('sa', 'Solutions Architect', 145, 12, 6);

-- demand
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'SQL', 188);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Python', 174);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Cloud (AWS / GCP)', 106);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Docker', 86);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'ETL / data pipeline', 85);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Git / version control', 73);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Data warehouse concepts', 59);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Apache Spark', 54);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'สื่อสารกับ stakeholder', 53);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Linux / shell', 46);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'System / pipeline architecture', 218);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'Apache Kafka', 147);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'Cloud cost optimisation', 125);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'Cloud (AWS / GCP)', 121);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'นำทีม / mentoring', 107);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'Data governance', 79);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'SQL', 72);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'Terraform / IaC', 60);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Git / version control', 551);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'REST API', 529);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'SQL', 478);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Python', 347);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Java / Spring Boot', 317);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Docker', 292);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'OOP / design patterns', 269);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Unit testing', 232);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Linux / shell', 216);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'CI/CD', 196);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Cloud (AWS / GCP)', 166);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'สื่อสารกับ stakeholder', 133);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'System / pipeline architecture', 502);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'Microservices', 383);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'Kubernetes', 351);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'นำทีม / mentoring', 332);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'Cloud (AWS / GCP)', 312);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'Performance tuning / scaling', 265);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'Message queue (Kafka / RabbitMQ)', 216);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'Security / OWASP', 167);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'SQL', 300);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'Excel ขั้นสูง', 251);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'Power BI / Tableau', 221);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'Python', 172);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'สื่อสารกับ stakeholder', 161);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'สถิติเชิงพรรณนา', 137);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'การนำเสนอข้อมูลด้วยภาพ', 119);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'แปลโจทย์ธุรกิจเป็นคำถามเชิงข้อมูล', 105);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'Data cleaning / wrangling', 95);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'Google Analytics', 62);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'แปลโจทย์ธุรกิจเป็นคำถามเชิงข้อมูล', 229);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'A/B testing / การออกแบบการทดลอง', 185);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'Data modeling', 165);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'นำทีม / mentoring', 148);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'dbt / analytics engineering', 107);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'SQL', 97);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'Data governance', 80);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'Python', 67);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'Machine learning พื้นฐาน', 59);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'SQL', 47);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'PyTorch / TensorFlow', 43);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'Docker', 38);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'คณิตศาสตร์ / สถิติ', 35);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'Cloud (AWS / GCP)', 31);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'Deep learning', 28);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'Git / version control', 26);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'อ่านและ implement งานวิจัย', 21);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'MLOps / model deployment', 109);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'System / pipeline architecture', 97);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'Feature store / data pipeline', 77);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'Model monitoring / drift', 72);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'นำทีม / mentoring', 59);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'Distributed training', 48);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'Cloud cost optimisation', 38);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Linux / shell', 109);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Docker', 98);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'CI/CD', 91);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Kubernetes', 75);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Cloud (AWS / GCP)', 71);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Git / version control', 64);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Networking พื้นฐาน', 54);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Terraform / IaC', 47);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Monitoring / observability', 43);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'on-call / incident response', 40);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Python / scripting', 37);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'System / pipeline architecture', 212);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'on-call / incident response', 181);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'Kubernetes', 165);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'Cloud cost optimisation', 140);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'Security / compliance', 119);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'นำทีม / mentoring', 96);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'Terraform / IaC', 85);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'System / solution architecture', 113);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'Cloud (AWS / GCP)', 102);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'คุยกับลูกค้า / requirement gathering', 90);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'Microservices / integration', 75);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'Security / compliance', 66);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'นำทีม / mentoring', 59);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'Cost estimation / TCO', 35);

commit;
