-- Auto-generated from lib/data.ts — do not hand-edit, re-run scripts/gen-seed.ts instead
begin;
truncate table demand, feedback, skills, courses, roles, majors restart identity cascade;

-- majors
insert into majors (id, name, school, ready, note) values ('cs-tu', 'วิทยาการคอมพิวเตอร์', 'คณะวิทยาศาสตร์และเทคโนโลยี มธ.', true, 'หลักสูตรปรับปรุง พ.ศ. 2566 · ข้อมูลรายวิชาอ้างอิงเอกสารจริง');
insert into majors (id, name, school, ready, note) values ('stat-sci-tu', 'สถิติ — วิชาเอกสถิติศาสตร์', 'คณะวิทยาศาสตร์และเทคโนโลยี มธ. ศูนย์รังสิต', true, 'หลักสูตรปรับปรุง พ.ศ. 2566 · โครงการภาคปกติ · บางวิชาเลือกไม่มีเทอมกำกับตายตัวในแผน จึงประมาณจากวิชาบังคับก่อน — ระบุไว้ในหน้ารายวิชา');
insert into majors (id, name, school, ready, note) values ('stat-da-tu', 'สถิติ — วิชาเอกวิทยาการวิเคราะห์ข้อมูล', 'คณะวิทยาศาสตร์และเทคโนโลยี มธ. ศูนย์รังสิต', true, 'หลักสูตรปรับปรุง พ.ศ. 2566 · โครงการภาคพิเศษ · บางวิชาเลือกไม่มีเทอมกำกับตายตัวในแผน จึงประมาณจากวิชาบังคับก่อน — ระบุไว้ในหน้ารายวิชา');
insert into majors (id, name, school, ready, note) values ('it-tu', 'เทคโนโลยีสารสนเทศ', 'คณะวิทยาศาสตร์และเทคโนโลยี มธ.', false, NULL);
insert into majors (id, name, school, ready, note) values ('ce', 'วิศวกรรมคอมพิวเตอร์', 'คณะวิศวกรรมศาสตร์', false, NULL);

-- courses
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.103', 'การโปรแกรมคอมพิวเตอร์เบื้องต้น · Introduction to Computer Programming', 'ปี 1 · เทอม 1', 11);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.100', 'การพัฒนาเว็บแอปพลิเคชันเบื้องต้น · Basic Web Development', 'ปี 1 · เทอม 2', 12);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.111', 'แนวคิดเชิงวัตถุ · Object-Oriented Concepts', 'ปี 1 · เทอม 2', 12);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.216', 'โครงสร้างข้อมูลและขั้นตอนวิธี · Data Structures and Algorithms', 'ปี 2 · เทอม 1', 21);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.240', 'หลักการวิทยาการข้อมูล · Principles of Data Science', 'ปี 2 · เทอม 1', 21);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.251', 'ระบบฐานข้อมูล 1 · Database Systems 1', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.234', 'เครือข่ายคอมพิวเตอร์และความปลอดภัยทางไซเบอร์ · Computer Network and Cyber-Security', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.232', 'เทคโนโลยีกลุ่มเมฆเบื้องต้น · Introduction to Cloud Computing', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.261', 'วิศวกรรมซอฟต์แวร์เบื้องต้น · Introduction to Software Engineering', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.365', 'กระบวนการและไปป์ไลน์เดฟออปส์ · DevOps Pipelines and Processes', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.262', 'การทดสอบซอฟต์แวร์เบื้องต้น · Introduction to Software Testing', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.224', 'การดูแลและติดตามประสิทธิภาพระบบปฏิบัติการ · Linux Administration and Performance Monitoring', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.341', 'วิศวกรรมข้อมูลขนาดใหญ่ · Big Data Engineering', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.347', 'คลังข้อมูลและอัจฉริยะทางธุรกิจ · Data Warehousing and Business Intelligence', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.354', 'ระบบฐานข้อมูล 2 · Database Systems 2', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.246', 'การแสดงข้อมูล · Data Visualization', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.361', 'สถาปัตยกรรมซอฟต์แวร์บนคลาวด์ · Cloud-Based Software Architecting', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.372', 'การเรียนรู้ของเครื่อง · Machine Learning', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.343', 'การเรียนรู้เชิงลึก · Applied Deep Learning', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('cs-tu', 'คพ.367', 'แนวคิดการพัฒนาเว็บบริการ · Web Service Development Concepts', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.190', 'สัมมนาอาชีพ · Career Seminar', 'ปี 1 · เทอม 2', 12);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.211', 'สถิติ 1 · Statistics 1', 'ปี 1 · เทอม 1', 11);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.212', 'สถิติ 2 · Statistics 2', 'ปี 1 · เทอม 2', 12);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.221', 'วิทยาการข้อมูลเบื้องต้นและการประยุกต์ · Intro to Data Science and Its Applications', 'ปี 2 · เทอม 1', 21);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.246', 'ความรู้ทั่วไปเกี่ยวกับการประกันภัย · General Principles of Insurance', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.247', 'ตลาดการเงินและการลงทุนในหลักทรัพย์ · Financial Market and Portfolio Investment', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.271', 'ฐานข้อมูลและการเตรียมข้อมูลเบื้องต้น · Intro to Database and Data Preprocessing', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.276', 'วิทยาการวิเคราะห์ข้อมูลในตารางงาน · Spreadsheet Data Analytics', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.321', 'ทฤษฎีความน่าจะเป็นเบื้องต้น · Introductory Probability Theory', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.322', 'คณิตสถิติศาสตร์ 1 · Mathematical Statistics 1', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.332', 'การวิเคราะห์การถดถอยประยุกต์ · Applied Regression Analysis', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.333', 'ฝึกปฏิบัติงานทางสถิติ · Practical Experiences in Statistics', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.336', 'การควบคุมคุณภาพเชิงสถิติ · Statistical Quality Control', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.337', 'สถิติศาสตร์ไม่อิงพารามิเตอร์เบื้องต้น · Intro to Nonparametric Statistics', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.339', 'ประชากรศาสตร์ 1 · Demography 1', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.346', 'ทฤษฎีดอกเบี้ย · Theory of Interest', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.347', 'คณิตศาสตร์ประกันชีวิต 1 · Mathematics of Life Insurance 1', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.348', 'การวิเคราะห์เชิงปริมาณทางการเงิน · Quantitative Analysis in Finance', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.349', 'คณิตศาสตร์ประกันวินาศภัย · Casualty Actuarial Mathematics', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.351', 'การสำรวจตัวอย่างเบื้องต้น · Intro to Sample Surveys', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.371', 'วิทยาการวิเคราะห์เชิงทำนาย 1 · Predictive Analytics 1', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.376', 'การวิเคราะห์ข้อมูลและการคำนวณด้วยโปรแกรมสำเร็จรูปทางสถิติ · Data Analysis and Computing with Statistical Packages', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.378', 'การเล่าเรื่องจากข้อมูล · Data Storytelling', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.386', 'ชีวสถิติเบื้องต้น · Intro to Biostatistics', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.422', 'คณิตสถิติศาสตร์ 2 · Mathematical Statistics 2', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.428', 'หัวข้อพิเศษทางคณิตศาสตร์ประกันภัย · Special Topics in Actuarial Mathematics', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.431', 'การออกแบบการทดลอง · Experimental Design', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.436', 'การวิเคราะห์การตัดสินใจทางสถิติเบื้องต้น · Intro to Statistical Decision Analysis', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.437', 'ตรรกศาสตร์ฟัซซีสำหรับธุรกิจและการเงิน · Fuzzy Logic for Business and Finance', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.438', 'อนุกรมเวลาและการพยากรณ์ · Time Series and Forecasting', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.439', 'ประชากรศาสตร์ 2 · Demography 2', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.446', 'ตัวแบบค่าเสียหายขั้นพื้นฐาน · Basic Loss Models', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.447', 'คณิตศาสตร์ประกันชีวิต 2 · Mathematics of Life Insurance 2', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.448', 'อนุพันธ์ทางการเงินเชิงคณิตศาสตร์ · Mathematics of Financial Derivatives', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.449', 'สัมมนาคณิตศาสตร์ประกันภัย · Seminar in Actuarial Mathematics', 'ปี 4 · เทอม 2', 42);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.451', 'ระเบียบวิธีการวิจัย · Research Methodology', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.466', 'การวิจัยดำเนินงาน · Operations Research', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.468', 'วิทยาการวิเคราะห์ลูกค้าและการบริหารความสัมพันธ์ · Customer Analytics and CRM', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.476', 'การจำลองเบื้องต้น · Intro to Simulation', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.481', 'วิทยาการวิเคราะห์เชิงทำนาย 2 · Predictive Analytics 2', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.486', 'การวิเคราะห์หลายตัวแปรประยุกต์ · Applied Multivariate Analysis', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.487', 'การเรียนรู้เชิงสถิติเบื้องต้น · Intro to Statistical Learning', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.494', 'โครงงานพิเศษ 1 · Special Project 1', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.495', 'โครงงานพิเศษ 2 · Special Project 2', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.497', 'หัวข้อพิเศษ · Special Topics', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-sci-tu', 'ส.498', 'หัวข้อคัดสรร · Selected Topics', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.190', 'สัมมนาอาชีพ · Career Seminar', 'ปี 1 · เทอม 2', 12);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.211', 'สถิติ 1 · Statistics 1', 'ปี 1 · เทอม 1', 11);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.212', 'สถิติ 2 · Statistics 2', 'ปี 1 · เทอม 2', 12);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.221', 'วิทยาการข้อมูลเบื้องต้นและการประยุกต์ · Intro to Data Science and Its Applications', 'ปี 2 · เทอม 1', 21);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.246', 'ความรู้ทั่วไปเกี่ยวกับการประกันภัย · General Principles of Insurance', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.247', 'ตลาดการเงินและการลงทุนในหลักทรัพย์ · Financial Market and Portfolio Investment', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.271', 'ฐานข้อมูลและการเตรียมข้อมูลเบื้องต้น · Intro to Database and Data Preprocessing', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.276', 'วิทยาการวิเคราะห์ข้อมูลในตารางงาน · Spreadsheet Data Analytics', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.321', 'ทฤษฎีความน่าจะเป็นเบื้องต้น · Introductory Probability Theory', 'ปี 2 · เทอม 1', 21);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.322', 'คณิตสถิติศาสตร์ 1 · Mathematical Statistics 1', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.332', 'การวิเคราะห์การถดถอยประยุกต์ · Applied Regression Analysis', 'ปี 2 · เทอม 2', 22);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.333', 'ฝึกปฏิบัติงานทางสถิติ · Practical Experiences in Statistics', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.336', 'การควบคุมคุณภาพเชิงสถิติ · Statistical Quality Control', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.337', 'สถิติศาสตร์ไม่อิงพารามิเตอร์เบื้องต้น · Intro to Nonparametric Statistics', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.339', 'ประชากรศาสตร์ 1 · Demography 1', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.346', 'ทฤษฎีดอกเบี้ย · Theory of Interest', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.347', 'คณิตศาสตร์ประกันชีวิต 1 · Mathematics of Life Insurance 1', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.348', 'การวิเคราะห์เชิงปริมาณทางการเงิน · Quantitative Analysis in Finance', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.349', 'คณิตศาสตร์ประกันวินาศภัย · Casualty Actuarial Mathematics', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.351', 'การสำรวจตัวอย่างเบื้องต้น · Intro to Sample Surveys', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.371', 'วิทยาการวิเคราะห์เชิงทำนาย 1 · Predictive Analytics 1', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.376', 'การวิเคราะห์ข้อมูลและการคำนวณด้วยโปรแกรมสำเร็จรูปทางสถิติ · Data Analysis and Computing with Statistical Packages', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.378', 'การเล่าเรื่องจากข้อมูล · Data Storytelling', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.386', 'ชีวสถิติเบื้องต้น · Intro to Biostatistics', 'ปี 3 · เทอม 1', 31);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.422', 'คณิตสถิติศาสตร์ 2 · Mathematical Statistics 2', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.428', 'หัวข้อพิเศษทางคณิตศาสตร์ประกันภัย · Special Topics in Actuarial Mathematics', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.431', 'การออกแบบการทดลอง · Experimental Design', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.436', 'การวิเคราะห์การตัดสินใจทางสถิติเบื้องต้น · Intro to Statistical Decision Analysis', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.437', 'ตรรกศาสตร์ฟัซซีสำหรับธุรกิจและการเงิน · Fuzzy Logic for Business and Finance', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.438', 'อนุกรมเวลาและการพยากรณ์ · Time Series and Forecasting', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.439', 'ประชากรศาสตร์ 2 · Demography 2', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.446', 'ตัวแบบค่าเสียหายขั้นพื้นฐาน · Basic Loss Models', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.447', 'คณิตศาสตร์ประกันชีวิต 2 · Mathematics of Life Insurance 2', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.448', 'อนุพันธ์ทางการเงินเชิงคณิตศาสตร์ · Mathematics of Financial Derivatives', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.449', 'สัมมนาคณิตศาสตร์ประกันภัย · Seminar in Actuarial Mathematics', 'ปี 4 · เทอม 2', 42);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.451', 'ระเบียบวิธีการวิจัย · Research Methodology', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.466', 'การวิจัยดำเนินงาน · Operations Research', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.468', 'วิทยาการวิเคราะห์ลูกค้าและการบริหารความสัมพันธ์ · Customer Analytics and CRM', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.476', 'การจำลองเบื้องต้น · Intro to Simulation', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.481', 'วิทยาการวิเคราะห์เชิงทำนาย 2 · Predictive Analytics 2', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.486', 'การวิเคราะห์หลายตัวแปรประยุกต์ · Applied Multivariate Analysis', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.487', 'การเรียนรู้เชิงสถิติเบื้องต้น · Intro to Statistical Learning', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.494', 'โครงงานพิเศษ 1 · Special Project 1', 'ปี 3 · เทอม 2', 32);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.495', 'โครงงานพิเศษ 2 · Special Project 2', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.497', 'หัวข้อพิเศษ · Special Topics', 'ปี 4 · เทอม 1', 41);
insert into courses (major_id, code, name, when_label, ord) values ('stat-da-tu', 'ส.498', 'หัวข้อคัดสรร · Selected Topics', 'ปี 4 · เทอม 1', 41);

-- skills
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'SQL', 'คพ.251', 'คพ.251 ระบบฐานข้อมูล 1', 'หลักสูตรเขียนว่า “ภาษาสอบถาม / query languages” — คำว่า SQL ไม่ปรากฏในเอกสารหลักสูตรเลยแม้แต่ครั้งเดียว (ค้นทั้ง 162 หน้า)', NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Python', 'คพ.103', 'คพ.103 การโปรแกรมคอมพิวเตอร์เบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Python / scripting', 'คพ.103', 'คพ.103 การโปรแกรมคอมพิวเตอร์เบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'REST API', 'คพ.100', 'คพ.100 การพัฒนาเว็บแอปพลิเคชันเบื้องต้น', 'หลักสูตรเขียนว่า “เว็บแอปพลิเคชัน” — คำว่า REST ไม่ปรากฏในเอกสารหลักสูตรเลย', NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'OOP / design patterns', 'คพ.111', 'คพ.111 แนวคิดเชิงวัตถุ', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'โครงสร้างข้อมูล / อัลกอริทึม', 'คพ.216', 'คพ.216 โครงสร้างข้อมูลและขั้นตอนวิธี', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'สถิติเชิงพรรณนา', 'คพ.240', 'คพ.240 หลักการวิทยาการข้อมูล', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'คณิตศาสตร์ / สถิติ', 'คพ.240', 'คพ.240 หลักการวิทยาการข้อมูล', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Networking พื้นฐาน', 'คพ.234', 'คพ.234 เครือข่ายคอมพิวเตอร์และความปลอดภัยทางไซเบอร์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Cloud พื้นฐาน', 'คพ.232', 'คพ.232 เทคโนโลยีกลุ่มเมฆเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Git / version control', 'คพ.365', 'คพ.365 กระบวนการและไปป์ไลน์เดฟออปส์', 'เอกสารหลักสูตรเขียนว่า “การควบคุมเวอร์ชันของโค้ดด้วยกิท” — ทับศัพท์ไทย ค้นคำว่า Git ไม่เจอ', 'คพ.365 หน้า 74 · ฉบับอังกฤษเขียน code version control/git', true, true, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Docker', 'คพ.365', 'คพ.365 กระบวนการและไปป์ไลน์เดฟออปส์', 'เอกสารหลักสูตรเขียนว่า “คอนเทนเนอร์” — ชื่อหมวดหมู่ ไม่ใช่ชื่อผลิตภัณฑ์ ค้นคำว่า Docker ไม่เจอ', 'คพ.365 หน้า 74 · ฉบับอังกฤษเขียน container', true, true, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'CI/CD', 'คพ.365', 'คพ.365 กระบวนการและไปป์ไลน์เดฟออปส์', 'เอกสารหลักสูตรเขียนว่า “การสร้างซีไอซีดีไปป์ไลน์” — ทับศัพท์ไทย ค้นคำว่า CI/CD ไม่เจอ', 'คพ.365 หน้า 74 · ฉบับอังกฤษเขียน CI/CD pipeline', true, true, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Unit testing', 'คพ.261', 'คพ.261 วิศวกรรมซอฟต์แวร์เบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Data warehouse concepts', 'คพ.251', 'คพ.251 ครอบคลุมบางส่วน', NULL, NULL, false, false, true, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Cloud (AWS / GCP)', 'คพ.361', 'คพ.361 สถาปัตยกรรมซอฟต์แวร์บนคลาวด์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Apache Spark', 'คพ.341', 'คพ.341 วิศวกรรมข้อมูลขนาดใหญ่', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'ETL / data pipeline', 'คพ.341', 'คพ.341 วิศวกรรมข้อมูลขนาดใหญ่', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Data cleaning / wrangling', 'คพ.341', 'คพ.341 วิศวกรรมข้อมูลขนาดใหญ่', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'การนำเสนอข้อมูลด้วยภาพ', 'คพ.246', 'คพ.246 การแสดงข้อมูล', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Machine learning พื้นฐาน', 'คพ.372', 'คพ.372 การเรียนรู้ของเครื่อง', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Deep learning', 'คพ.343', 'คพ.343 การเรียนรู้เชิงลึก', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Data modeling', 'คพ.354', 'คพ.354 ระบบฐานข้อมูล 2', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Linux / shell', 'คพ.224', 'คพ.224 การดูแลและติดตามประสิทธิภาพระบบปฏิบัติการ', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Java / Spring Boot', NULL, 'หลักสูตรสอน OOP แต่ไม่สอนเฟรมเวิร์กนี้', 'ค้นคำว่า “Spring” ในเอกสารหลักสูตรทั้งฉบับ = พบ 0 ครั้ง · คำว่า “Java” พบ 1 ครั้ง อยู่ในคำว่า JavaScript', NULL, false, false, false, 'course', 'ประกาศเขียนว่า "เคยใช้ Spring Boot ในโปรเจกต์จริง" ไม่ใช่ "จบสาย Java" — หลักสูตรให้พื้น OOP มาแล้ว เหลือแค่เฟรมเวิร์ก', 'เขียน REST API ตัวที่เคยทำในวิชา คพ.100 ใหม่ด้วย Spring Boot ให้จบทั้งตัว', 'ประมาณ 1–2 สุดสัปดาห์ · ได้ repo เป็นหลักฐาน', NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Kubernetes', NULL, 'ไม่มีวิชาไหนในหลักสูตรสอน', 'ค้นคำว่า “Kubernetes” ในเอกสารหลักสูตร = พบ 0 ครั้ง', NULL, false, false, false, 'course', NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Terraform / IaC', NULL, 'ไม่มีวิชาไหนในหลักสูตรสอน', NULL, NULL, false, false, false, 'course', NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Apache Kafka', NULL, 'ไม่มีวิชาไหนในหลักสูตรสอน', NULL, NULL, false, false, false, 'course', NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Message queue (Kafka / RabbitMQ)', NULL, 'คพ.366 กล่าวถึงคิวข้อความ แต่ไม่ระบุเครื่องมือ', 'เอกสารเขียนว่า “สถาปัตยกรรมแบบแยกส่วนด้วยการใช้คิวข้อความ” — ไม่มีชื่อผลิตภัณฑ์', NULL, false, false, false, 'course', NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'สื่อสารกับ stakeholder', NULL, 'ได้จากการทำงานจริงเท่านั้น', NULL, NULL, false, false, false, 'work', NULL, NULL, NULL, 'ฝึกงาน ปี 3 หรือรับงานที่มีลูกค้าจริง');
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Requirements gathering', NULL, 'ได้จากการทำงานจริงเท่านั้น', NULL, NULL, false, false, false, 'work', NULL, NULL, NULL, 'รับงาน freelance หรือทำโปรเจกต์ให้หน่วยงานจริงในมหาวิทยาลัย');
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'อ่านและ implement งานวิจัย', NULL, 'ได้จากโครงงานหรือแล็บวิจัย', NULL, NULL, false, false, false, 'work', NULL, NULL, NULL, 'ขอเข้าแล็บอาจารย์ หรือทำโปรเจกต์ปี 4 สายนี้');
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('cs-tu', 'Cost estimation / TCO', NULL, 'ได้จากการทำงานจริงเท่านั้น', NULL, NULL, false, false, false, 'work', NULL, NULL, NULL, 'ต้องเคยเสนอราคาให้ลูกค้าจริง');
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'SQL', 'ส.271', 'ส.271 ฐานข้อมูลและการเตรียมข้อมูลเบื้องต้น', 'เอกสารเขียนว่า “ภาษาคิวรีที่มีโครงสร้าง” — ไม่มีคำว่า SQL เลย ฉบับอังกฤษเขียน “structured query language” เต็มคำ', 'ส.271 · ส.221 ก็กล่าวถึงเช่นกัน (“การจัดการข้อมูลด้วยเอสคิวแอลเบื้องต้น” — ทับศัพท์ไทย ไม่ใช่ตัวอักษรละติน SQL)', false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Python', 'ส.221', 'ส.221 วิทยาการข้อมูลเบื้องต้นและการประยุกต์ — กล่าวถึงไพทอนตรงตัว', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Power BI / Tableau', 'ส.221', 'ส.221 วิทยาการข้อมูลเบื้องต้นและการประยุกต์ — กล่าวถึง Tableau และ Power BI ตรงตัว', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Excel ขั้นสูง', 'ส.276', 'ส.276 วิทยาการวิเคราะห์ข้อมูลในตารางงาน', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'VBA (Visual Basic for Applications)', 'ส.276', 'ส.276 วิทยาการวิเคราะห์ข้อมูลในตารางงาน — กล่าวถึง VBA ตรงตัว', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'สถิติเชิงพรรณนา', 'ส.211', 'ส.211 สถิติ 1', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'คณิตศาสตร์ / สถิติ', 'ส.321', 'ส.321 ทฤษฎีความน่าจะเป็นเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Data cleaning / wrangling', 'ส.271', 'ส.271 ฐานข้อมูลและการเตรียมข้อมูลเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Machine learning พื้นฐาน', 'ส.371', 'ส.371 วิทยาการวิเคราะห์เชิงทำนาย 1 — ระบุชื่ออัลกอริทึมตรงตัว: logistic regression, k-NN, decision tree, random forest, Naive Bayes, ANN, SVM (ส.487 ครอบคลุมเพิ่มเติม)', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Deep learning', 'ส.481', 'ส.481 วิทยาการวิเคราะห์เชิงทำนาย 2 — โครงข่ายประสาทเทียมคอนโวลูชัน/แบบวนกลับ (CNN/RNN) ตรงตัว', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'การนำเสนอข้อมูลด้วยภาพ', 'ส.378', 'ส.378 การเล่าเรื่องจากข้อมูล', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'A/B testing / การออกแบบการทดลอง', 'ส.431', 'ส.431 การออกแบบการทดลอง', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Regression analysis', 'ส.332', 'ส.332 การวิเคราะห์การถดถอยประยุกต์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Relational database model', 'ส.271', 'ส.271 ฐานข้อมูลและการเตรียมข้อมูลเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Classification / Regression', 'ส.221', 'ส.221 วิทยาการข้อมูลเบื้องต้นและการประยุกต์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Decision tree / Random forest / Naive Bayes', 'ส.371', 'ส.371 วิทยาการวิเคราะห์เชิงทำนาย 1', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'K-means clustering / PCA', 'ส.481', 'ส.481 วิทยาการวิเคราะห์เชิงทำนาย 2', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Regularization (Ridge / Lasso)', 'ส.487', 'ส.487 การเรียนรู้เชิงสถิติเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'PCA / Factor / Discriminant analysis', 'ส.486', 'ส.486 การวิเคราะห์หลายตัวแปรประยุกต์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Time series forecasting (ARIMA)', 'ส.438', 'ส.438 อนุกรมเวลาและการพยากรณ์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Customer analytics / CRM / Churn prediction', 'ส.468', 'ส.468 วิทยาการวิเคราะห์ลูกค้าและการบริหารความสัมพันธ์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'โปรแกรมสำเร็จรูปทางสถิติ', 'ส.376', 'ส.376 การวิเคราะห์ข้อมูลและการคำนวณด้วยโปรแกรมสำเร็จรูปทางสถิติ', 'เอกสารไม่ระบุชื่อโปรแกรม (SPSS/SAS/R/Minitab) เขียนแค่ “โปรแกรมสำเร็จรูปทางสถิติ” ตลอดทั้งหลักสูตร — จุดที่แม้แต่มนุษย์อ่านก็ยังไม่รู้ว่าเป็นเครื่องมือตัวไหนจริง', NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Monte Carlo / MCMC simulation', 'ส.476', 'ส.476 การจำลองเบื้องต้น — ส.376 ก็กล่าวถึงเช่นกัน', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Survey sampling methodology', 'ส.351', 'ส.351 การสำรวจตัวอย่างเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Statistical process control', 'ส.336', 'ส.336 การควบคุมคุณภาพเชิงสถิติ', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Linear programming / Optimization', 'ส.466', 'ส.466 การวิจัยดำเนินงาน', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Biostatistics / Survival analysis', 'ส.386', 'ส.386 ชีวสถิติเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Demographic analysis', 'ส.339', 'ส.339 ประชากรศาสตร์ 1 (ส.439 ประชากรศาสตร์ 2 ครอบคลุมเพิ่มเติม)', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'ANOVA / Chi-square test', 'ส.212', 'ส.212 สถิติ 2', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Nonparametric statistics', 'ส.337', 'ส.337 สถิติศาสตร์ไม่อิงพารามิเตอร์เบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'MLE / Bayesian inference', 'ส.322', 'ส.322 คณิตสถิติศาสตร์ 1 (ส.422 คณิตสถิติศาสตร์ 2 ครอบคลุมเพิ่มเติม)', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Decision theory', 'ส.436', 'ส.436 การวิเคราะห์การตัดสินใจทางสถิติเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Fuzzy logic', 'ส.437', 'ส.437 ตรรกศาสตร์ฟัซซีสำหรับธุรกิจและการเงิน', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Insurance fundamentals / Risk management', 'ส.246', 'ส.246 ความรู้ทั่วไปเกี่ยวกับการประกันภัย', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Interest / annuity theory', 'ส.346', 'ส.346 ทฤษฎีดอกเบี้ย', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Life insurance mathematics', 'ส.347', 'ส.347 คณิตศาสตร์ประกันชีวิต 1 (ส.447 ภาค 2 ครอบคลุมเพิ่มเติม)', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Quantitative finance / Capital budgeting', 'ส.348', 'ส.348 การวิเคราะห์เชิงปริมาณทางการเงิน', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Ratemaking / Loss reserving', 'ส.349', 'ส.349 คณิตศาสตร์ประกันวินาศภัย', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Loss modeling / Value-at-Risk (VaR)', 'ส.446', 'ส.446 ตัวแบบค่าเสียหายขั้นพื้นฐาน', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Financial derivatives / Options pricing', 'ส.448', 'ส.448 อนุพันธ์ทางการเงินเชิงคณิตศาสตร์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Portfolio management / Security analysis', 'ส.247', 'ส.247 ตลาดการเงินและการลงทุนในหลักทรัพย์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'Actuarial special topics / seminar', 'ส.428', 'ส.428 หัวข้อพิเศษทางคณิตศาสตร์ประกันภัย (ส.449 สัมมนาฯ ต่อเนื่องกัน)', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'ระเบียบวิธีการวิจัย', 'ส.451', 'ส.451 ระเบียบวิธีการวิจัย', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'โครงงานประยุกต์', 'ส.494', 'ส.494 โครงงานพิเศษ 1 (ส.495 ภาค 2 ต่อเนื่องกัน)', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-sci-tu', 'ฝึกงานภาคสถิติ (200 ชม.)', 'ส.333', 'ส.333 ฝึกปฏิบัติงานทางสถิติ — หลักสูตรบังคับฝึกงานจริงอย่างน้อย 200 ชั่วโมง', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'SQL', 'ส.271', 'ส.271 ฐานข้อมูลและการเตรียมข้อมูลเบื้องต้น', 'เอกสารเขียนว่า “ภาษาคิวรีที่มีโครงสร้าง” — ไม่มีคำว่า SQL เลย ฉบับอังกฤษเขียน “structured query language” เต็มคำ', 'ส.271 · ส.221 ก็กล่าวถึงเช่นกัน (“การจัดการข้อมูลด้วยเอสคิวแอลเบื้องต้น” — ทับศัพท์ไทย ไม่ใช่ตัวอักษรละติน SQL)', false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Python', 'ส.221', 'ส.221 วิทยาการข้อมูลเบื้องต้นและการประยุกต์ — กล่าวถึงไพทอนตรงตัว', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Power BI / Tableau', 'ส.221', 'ส.221 วิทยาการข้อมูลเบื้องต้นและการประยุกต์ — กล่าวถึง Tableau และ Power BI ตรงตัว', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Excel ขั้นสูง', 'ส.276', 'ส.276 วิทยาการวิเคราะห์ข้อมูลในตารางงาน', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'VBA (Visual Basic for Applications)', 'ส.276', 'ส.276 วิทยาการวิเคราะห์ข้อมูลในตารางงาน — กล่าวถึง VBA ตรงตัว', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'สถิติเชิงพรรณนา', 'ส.211', 'ส.211 สถิติ 1', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'คณิตศาสตร์ / สถิติ', 'ส.321', 'ส.321 ทฤษฎีความน่าจะเป็นเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Data cleaning / wrangling', 'ส.271', 'ส.271 ฐานข้อมูลและการเตรียมข้อมูลเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Machine learning พื้นฐาน', 'ส.371', 'ส.371 วิทยาการวิเคราะห์เชิงทำนาย 1 — ระบุชื่ออัลกอริทึมตรงตัว: logistic regression, k-NN, decision tree, random forest, Naive Bayes, ANN, SVM (ส.487 ครอบคลุมเพิ่มเติม)', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Deep learning', 'ส.481', 'ส.481 วิทยาการวิเคราะห์เชิงทำนาย 2 — โครงข่ายประสาทเทียมคอนโวลูชัน/แบบวนกลับ (CNN/RNN) ตรงตัว', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'การนำเสนอข้อมูลด้วยภาพ', 'ส.378', 'ส.378 การเล่าเรื่องจากข้อมูล', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'A/B testing / การออกแบบการทดลอง', 'ส.431', 'ส.431 การออกแบบการทดลอง', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Regression analysis', 'ส.332', 'ส.332 การวิเคราะห์การถดถอยประยุกต์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Relational database model', 'ส.271', 'ส.271 ฐานข้อมูลและการเตรียมข้อมูลเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Classification / Regression', 'ส.221', 'ส.221 วิทยาการข้อมูลเบื้องต้นและการประยุกต์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Decision tree / Random forest / Naive Bayes', 'ส.371', 'ส.371 วิทยาการวิเคราะห์เชิงทำนาย 1', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'K-means clustering / PCA', 'ส.481', 'ส.481 วิทยาการวิเคราะห์เชิงทำนาย 2', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Regularization (Ridge / Lasso)', 'ส.487', 'ส.487 การเรียนรู้เชิงสถิติเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'PCA / Factor / Discriminant analysis', 'ส.486', 'ส.486 การวิเคราะห์หลายตัวแปรประยุกต์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Time series forecasting (ARIMA)', 'ส.438', 'ส.438 อนุกรมเวลาและการพยากรณ์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Customer analytics / CRM / Churn prediction', 'ส.468', 'ส.468 วิทยาการวิเคราะห์ลูกค้าและการบริหารความสัมพันธ์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'โปรแกรมสำเร็จรูปทางสถิติ', 'ส.376', 'ส.376 การวิเคราะห์ข้อมูลและการคำนวณด้วยโปรแกรมสำเร็จรูปทางสถิติ', 'เอกสารไม่ระบุชื่อโปรแกรม (SPSS/SAS/R/Minitab) เขียนแค่ “โปรแกรมสำเร็จรูปทางสถิติ” ตลอดทั้งหลักสูตร — จุดที่แม้แต่มนุษย์อ่านก็ยังไม่รู้ว่าเป็นเครื่องมือตัวไหนจริง', NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Monte Carlo / MCMC simulation', 'ส.476', 'ส.476 การจำลองเบื้องต้น — ส.376 ก็กล่าวถึงเช่นกัน', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Survey sampling methodology', 'ส.351', 'ส.351 การสำรวจตัวอย่างเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Statistical process control', 'ส.336', 'ส.336 การควบคุมคุณภาพเชิงสถิติ', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Linear programming / Optimization', 'ส.466', 'ส.466 การวิจัยดำเนินงาน', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Biostatistics / Survival analysis', 'ส.386', 'ส.386 ชีวสถิติเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Demographic analysis', 'ส.339', 'ส.339 ประชากรศาสตร์ 1 (ส.439 ประชากรศาสตร์ 2 ครอบคลุมเพิ่มเติม)', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'ANOVA / Chi-square test', 'ส.212', 'ส.212 สถิติ 2', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Nonparametric statistics', 'ส.337', 'ส.337 สถิติศาสตร์ไม่อิงพารามิเตอร์เบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'MLE / Bayesian inference', 'ส.322', 'ส.322 คณิตสถิติศาสตร์ 1 (ส.422 คณิตสถิติศาสตร์ 2 ครอบคลุมเพิ่มเติม)', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Decision theory', 'ส.436', 'ส.436 การวิเคราะห์การตัดสินใจทางสถิติเบื้องต้น', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Fuzzy logic', 'ส.437', 'ส.437 ตรรกศาสตร์ฟัซซีสำหรับธุรกิจและการเงิน', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Insurance fundamentals / Risk management', 'ส.246', 'ส.246 ความรู้ทั่วไปเกี่ยวกับการประกันภัย', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Interest / annuity theory', 'ส.346', 'ส.346 ทฤษฎีดอกเบี้ย', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Life insurance mathematics', 'ส.347', 'ส.347 คณิตศาสตร์ประกันชีวิต 1 (ส.447 ภาค 2 ครอบคลุมเพิ่มเติม)', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Quantitative finance / Capital budgeting', 'ส.348', 'ส.348 การวิเคราะห์เชิงปริมาณทางการเงิน', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Ratemaking / Loss reserving', 'ส.349', 'ส.349 คณิตศาสตร์ประกันวินาศภัย', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Loss modeling / Value-at-Risk (VaR)', 'ส.446', 'ส.446 ตัวแบบค่าเสียหายขั้นพื้นฐาน', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Financial derivatives / Options pricing', 'ส.448', 'ส.448 อนุพันธ์ทางการเงินเชิงคณิตศาสตร์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Portfolio management / Security analysis', 'ส.247', 'ส.247 ตลาดการเงินและการลงทุนในหลักทรัพย์', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'Actuarial special topics / seminar', 'ส.428', 'ส.428 หัวข้อพิเศษทางคณิตศาสตร์ประกันภัย (ส.449 สัมมนาฯ ต่อเนื่องกัน)', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'ระเบียบวิธีการวิจัย', 'ส.451', 'ส.451 ระเบียบวิธีการวิจัย', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'โครงงานประยุกต์', 'ส.494', 'ส.494 โครงงานพิเศษ 1 (ส.495 ภาค 2 ต่อเนื่องกัน)', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);
insert into skills (major_id, key, code, note, alias, src, hidden, early_in_term, partial, kind, proof, act, time_estimate, route) values ('stat-da-tu', 'ฝึกงานภาคสถิติ (200 ชม.)', 'ส.333', 'ส.333 ฝึกปฏิบัติงานทางสถิติ — หลักสูตรบังคับฝึกงานจริงอย่างน้อย 200 ชั่วโมง', NULL, NULL, false, false, false, NULL, NULL, NULL, NULL, NULL);

-- roles
insert into roles (id, name, posts, jr_posts, fit) values ('de', 'Data Engineer', 480, 214, 1);
insert into roles (id, name, posts, jr_posts, fit) values ('be', 'Software Engineer (Backend)', 1240, 612, 2);
insert into roles (id, name, posts, jr_posts, fit) values ('da', 'Data Analyst', 610, 341, 3);
insert into roles (id, name, posts, jr_posts, fit) values ('ml', 'ML Engineer', 210, 74, 4);
insert into roles (id, name, posts, jr_posts, fit) values ('do', 'DevOps / SRE', 390, 118, 5);
insert into roles (id, name, posts, jr_posts, fit) values ('sa', 'Solutions Architect', 145, 12, 6);

-- demand
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'SQL', 188);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Python', 174);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Cloud (AWS / GCP)', 106);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Docker', 86);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'ETL / data pipeline', 85);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Git / version control', 73);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Data warehouse concepts', 59);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Apache Spark', 54);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'สื่อสารกับ stakeholder', 53);
insert into demand (role_id, level, skill_key, count) values ('de', 'jr', 'Linux / shell', 46);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'System / pipeline architecture', 218);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'Apache Kafka', 147);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'Cloud cost optimisation', 125);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'Cloud (AWS / GCP)', 121);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'นำทีม / mentoring', 107);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'Data governance', 79);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'SQL', 72);
insert into demand (role_id, level, skill_key, count) values ('de', 'sr', 'Terraform / IaC', 60);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Git / version control', 551);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'REST API', 529);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'SQL', 478);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Python', 347);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Java / Spring Boot', 317);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Docker', 292);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'OOP / design patterns', 269);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Unit testing', 232);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Linux / shell', 216);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'CI/CD', 196);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'Cloud (AWS / GCP)', 166);
insert into demand (role_id, level, skill_key, count) values ('be', 'jr', 'สื่อสารกับ stakeholder', 133);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'System / pipeline architecture', 502);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'Microservices', 383);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'Kubernetes', 351);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'นำทีม / mentoring', 332);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'Cloud (AWS / GCP)', 312);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'Performance tuning / scaling', 265);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'Message queue (Kafka / RabbitMQ)', 216);
insert into demand (role_id, level, skill_key, count) values ('be', 'sr', 'Security / OWASP', 167);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'SQL', 300);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'Excel ขั้นสูง', 251);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'Power BI / Tableau', 221);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'Python', 172);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'สื่อสารกับ stakeholder', 161);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'สถิติเชิงพรรณนา', 137);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'การนำเสนอข้อมูลด้วยภาพ', 119);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'แปลโจทย์ธุรกิจเป็นคำถามเชิงข้อมูล', 105);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'Data cleaning / wrangling', 95);
insert into demand (role_id, level, skill_key, count) values ('da', 'jr', 'Google Analytics', 62);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'แปลโจทย์ธุรกิจเป็นคำถามเชิงข้อมูล', 229);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'A/B testing / การออกแบบการทดลอง', 185);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'Data modeling', 165);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'นำทีม / mentoring', 148);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'dbt / analytics engineering', 107);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'SQL', 97);
insert into demand (role_id, level, skill_key, count) values ('da', 'sr', 'Data governance', 80);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'Python', 67);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'Machine learning พื้นฐาน', 59);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'SQL', 47);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'PyTorch / TensorFlow', 43);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'Docker', 38);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'คณิตศาสตร์ / สถิติ', 35);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'Cloud (AWS / GCP)', 31);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'Deep learning', 28);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'Git / version control', 26);
insert into demand (role_id, level, skill_key, count) values ('ml', 'jr', 'อ่านและ implement งานวิจัย', 21);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'MLOps / model deployment', 109);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'System / pipeline architecture', 97);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'Feature store / data pipeline', 77);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'Model monitoring / drift', 72);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'นำทีม / mentoring', 59);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'Distributed training', 48);
insert into demand (role_id, level, skill_key, count) values ('ml', 'sr', 'Cloud cost optimisation', 38);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Linux / shell', 109);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Docker', 98);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'CI/CD', 91);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Kubernetes', 75);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Cloud (AWS / GCP)', 71);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Git / version control', 64);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Networking พื้นฐาน', 54);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Terraform / IaC', 47);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Monitoring / observability', 43);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'on-call / incident response', 40);
insert into demand (role_id, level, skill_key, count) values ('do', 'jr', 'Python / scripting', 37);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'System / pipeline architecture', 212);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'on-call / incident response', 181);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'Kubernetes', 165);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'Cloud cost optimisation', 140);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'Security / compliance', 119);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'นำทีม / mentoring', 96);
insert into demand (role_id, level, skill_key, count) values ('do', 'sr', 'Terraform / IaC', 85);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'System / solution architecture', 113);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'Cloud (AWS / GCP)', 102);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'คุยกับลูกค้า / requirement gathering', 90);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'Microservices / integration', 75);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'Security / compliance', 66);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'นำทีม / mentoring', 59);
insert into demand (role_id, level, skill_key, count) values ('sa', 'sr', 'Cost estimation / TCO', 35);

commit;
